version: '3'
services:

  gnugraf_presentation:
    container_name: GnuGraf_Presentation
    image: dolly_presentation
    privileged: true
    environment:
      - DISPLAY=${DISPLAY} 
    volumes:
      - ./Presentation:/root/Presentation
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
    network_mode: host
    stdin_open: true
    tty: true
